### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by imitn** [RedBeardLab/rediSQL#14]
rediSQL-master]# make
gcc -c -Wpedantic -Wall -fPIC -IRedisModulesSDK/ -Bstatic rediSQL.c -o rediSQL.o
cc1: error: unrecognized command line option "-Wpedantic"
make: *** [all] Error 1

**Comment by imitn** [comment]
It executes successfully when I remove the option of "-Wpedantic" from the Makefile file

**Comment by siscia** [comment]
Thanks! 

Anyway it is kinda weird, it should be an option recognized by gcc https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

What version of gcc are you using?

**Comment by siscia** [comment]
I changed the Makefile a little bit but nothing related to -Wpedantic, I tried a fresh compilation on my machine and it works pretty well.

```
simo@simo:/tmp$ git clone git@github.com:RedBeardLab/rediSQL.git
Cloning into 'rediSQL'...
remote: Counting objects: 1519, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1519 (delta 0), reused 0 (delta 0), pack-reused 1516
Receiving objects: 100% (1519/1519), 7.35 MiB | 355.00 KiB/s, done.
Resolving deltas: 100% (572/572), done.
Checking connectivity... done.
simo@simo:/tmp$ cd rediSQL/
simo@simo:/tmp/rediSQL$ git branch 
* master
simo@simo:/tmp/rediSQL$ make
gcc -fPIC -c -o sqlite3.o sqlite3.c
gcc -c -Wpedantic -Wall -fPIC -IRedisModulesSDK/ -Bstatic rediSQL.c -o rediSQL.o
ld -o rediSQL.so rediSQL.o sqlite3.o RedisModulesSDK/rmutil/librmutil.a -shared -lc
simo@simo:/tmp/rediSQL$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

As you can see there is the `-Wpedantic` option.

`-Wpedantic` is more a compiler help to the developers, it highlights any sort of problem in a very, well, pedantic, way.
You actually don't need it to successfully compile the project. You want it while you are developing so that if you do something not too "clean" it will highlight it.

Please note, that the version on the master is extremely slow, I am working on something way better, faster and that doesn't block the redis thread.
If you are simpling looking around the master version is just okay, the source is quite easy to read and pretty straightforward, if you need more throughput and lower latency just ask and I will release the prototype for the faster version.

I am considering to re-write this in Rust, because the very fastest version, with all the functionality, has some problem, problem that I can't figure out but I believe is related to some sort of memory corruption.

Feel free to share your user case.

**Comment by imitn** [comment]
Thank you for your replay.  The version of gcc I use is shown as follows. 
# gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by siscia** [comment]
Great!

This is the relevant part of the documentation for your version of gcc :
https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gcc/Warning-Options.html#Warning-Options

As you can see -Wpedantic is not included, so it completely makes sense that your compilation with that option fails.

I am looking at this issues with more attention, and I am considering to switch to different command line options to support older compilers, but I first need to understand those option properly.

For you convenience I also made a release here on GitHub.

I am keen to close the issues.

If you tried the software, any feedback is very very appreciated.

If you had any problem, feel free to open an issues, if you had any suggestion, feel free to open an issues, if you find this a total mess and a complete waste of your time feel free to send me an email :)

**Comment by imitn** [comment]
Thanks for your patient answer, I get it and will to close the issues.

**Comment by siscia** [comment]
It was my pleasure, we do open source to learn from each other and move forward our community.

Have a great Day :)

Simone
