### ISSUE TITLE
redis.exceptions.ResponseError: Wrong number of arguments, it accepts 3

### ISSUE THREAD

**Issue by mmmcorpsvit** [RedBeardLab/rediSQL#33]
try use you soft from https://hub.docker.com/r/siscia/redisql/, but get error
python rediSQL_bench.py
```python
Starting performance test
Creating tables
Traceback (most recent call last):
  File "rediSQL_bench.py", line 162, in <module>
    prepare_tables(redis_pool)
  File "rediSQL_bench.py", line 31, in prepare_tables
    r.execute_command("REDISQL.EXEC", t)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: Wrong number of arguments, it accepts 3
```
1. what i do wrong?
2. i good understand what all data store in Redis, but use sqlite:memory how backend and possible use any extension for sqllite? and this do?

**Comment by siscia** [comment]
Hi!

Sorry you are doing nothing wrong, the code in the performance benchmark is wrong and outdated, python was the bottle neck and not RediSQL. As well the docker images with runs the version 3.1 if I remember correctly.

So, how to test the performance of RediSQL? The best thing is to use the redis-benchmark tool that comes along any Redis server.

I am from mobile now and I can't check all the commands, however, after you get RediSQL run ( even on a docker instance) you can do something like this:

```
.\redis-cli REDISQL.CREATE_DB DB
.\redis-cli REDISQL.EXEC DB "create table foo(a int, b int)"
.\redis-benchmark REDISQL.EXEC DB "insert into foo values(1,2)"
```

Again, I am just writing this command from top of my head, hence they may be wrong, bit the general idea is correct.


I am not sure about your second question.
So RediSQL can store data both in memory or in a file.
If you create a database passing as argument a filename it will store the data in such file.

```
REDISQL.CREATE_DB DB /home/foo/test.sqlite
```

It will create a database that writes on the "home/foo/test.sqlite" file.

For what concerns extension, it really depends on what you mean here. I don't provide an interface to load a custom extension, however I embed the most common used provide by SQLite. In particular the JSON1 extension and the FTS extension are embedded along with few others.

I hope I answered your questions. Anyway everything is explained in more details on the documentation along with examples!

If you have more questions please let me know! Otherwise feel free to close the issue. (Or you can leave it open so it can serve as a reminder to eliminate the wrong benchmark code.)

Cheers,
Simone

**Comment by mmmcorpsvit** [comment]
th for wide answer, yet have questions:
1. how can get datatype returned field? All data return how bytes for Python.
2. how get version installed rediSQL module? After load redis dont write anything info about version
3. try use rediSQL data in django admin part, this require QuerySet cast rediSQL data. Are any easy way to cast rediSQL to Django ORM Model with QuerySet? I try 2 days, but without successful( Maybe you have this sample? Please help with this part

p.s. sorry my poor English

**Comment by siscia** [comment]
Thanks for your feedback! Your questions are really useful!

I am a little busy right now but I will come back to you very soon answering all your question!

Very quickly, looking into the documentation of QuerySet it seems like the `.query` field contains the SQL generated for you. Is that not enough? Just get the SQL and pipe it into RediSQL...

Do you have some code where I can experiment? It would make me answering you much much faster.

**Comment by mmmcorpsvit** [comment]
i prepare code sample in closest time and share, very thanks for you help!)

**Comment by siscia** [comment]
I close for now!
