### ISSUE TITLE
redisql.create_statement  command has error

### ISSUE THREAD

**Issue by digo1985** [RedBeardLab/rediSQL#42]
redisql.create_statement DB 'INSERT INTO table_aa (A,B) VALUES (?1,?2);'

there appears error
(error) Wrong number of arguments, it accepts 4

and I change the command like redisql.create_statement DB 'INSERT INTO table_aa (A,B) VALUES (?,?);'
the error also appears.

**Comment by siscia** [comment]
Hi!

You are indeed missing a parameter.

When you create a statement you need to associate a name to the statement itself, so that you can invoke it.

Your command should be something like:

REDISQL.CRETATE_STATEMENT DB insert_user 'INSERT INTO table_aa (A,B) VALUES (?,?);'

Here the documentation for the particular command: http://redisql.redbeardlab.com/rediSQL/references/#redisqlcreate_statement

Can I make it clearer somehow?

**Comment by digo1985** [comment]
Thanks！！
Now,it's ok!
Thanks again!

**Comment by siscia** [comment]
Perfect!

For any other question, please feel free to open another issue
