### ISSUE TITLE
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible

### ISSUE THREAD

**Issue by digo1985** [RedBeardLab/rediSQL#45]
.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: (null) (base: (nil))
Module: /usr/local/src/redis-5.0.3/modules/redisql_v0.9.2_x86_64.so (base 0x7f449c010000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=(nil) -D -b binary -m i386:x86-64 /tmp/dump.bin
------

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/antirez/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.

The above log information appears after I run a more complicated SQL statement. But the data in my database table is empty

**Comment by siscia** [comment]
Can you share what statement you are running?

That seems like the result of `make test` in redis.

Is this reproducible?

**Comment by digo1985** [comment]
Yes, this is reproducible ,when I emptied the data in the database table and executed the statement, I still have this error.
At the same time, the table structure is also deleted.
When my statement returns with three text field types, there will be an exception(the strange thing is that I execute the statement directly in the Xshell terminal, it can return the result, but the exception will appear when I use the jedis client.), but when I return three count results, it is ok.

When  I start with select  c.title,c.displayAnswer,c.matchSymbol ......(title,displayAnswer field contain Chinese characters)  will appear the error. but when I start with  COUNT(1) as matchedNum ...... it is right.

**Comment by siscia** [comment]
Hi,

thank! It is very important that the bug is reproducible.

Usually the procedure to get it fixed is the following.

- [x] The bug is discovered (Thank you!)
- [x] We make sure the bug is reproducible (Thank you!)
- [ ] We encode the bug in the test suite
- [ ] We run the whole test suite to make sure that the bug fail
- [ ] We think really hard & code a solution
- [ ] We run again the whole test suite hoping that everything will pass
- [ ] If everything went fine we release a new version with the bug fixed.

Now, we need to encode the bug in our test suite.

You can either do it yourself with a pull request (this is the test file: https://github.com/RedBeardLab/rediSQL/blob/master/test/correctness/test.py) or if you provide me clear instruction I will do it myself.

I am expecting a sequence of instruction to run against RediSQL, something like:

1. Crate a DB `REDISQL.CREATE_DB DB`
2. Create a table `REDISQL.EXEC DB "create table ..."`
3. Add data to the table: `REDISQL:EXEC DB "insert into ..."`
4. Delete the data: ___FILL THE BLANK____
5. Other necessary steps: ___ FILL THE BLANK___
6. Here the bug: `SELECT ...`

Thanks so much for reporting the problem!

**Comment by digo1985** [comment]
Hi,Unfortunately,I am a javaer,I am not good at python,Could you send me an email? My email address is jide918@163.com, I will send you an email about the entire sql statement, because my sql statement is long. And some information about the company is best not to be public

**Comment by siscia** [comment]
I just reached out by email!

**Comment by siscia** [comment]
@digo1985 the problem persist?

**Comment by digo1985** [comment]
> @digo1985 the problem persist?

I have Solved by shortening the SQL statement,thks.

**Comment by siscia** [comment]
Which is great!

But not quite the solution I was hoping for.

We can investigate more but I would need the debug logs.

I close the issue for now, feel free to re-open it!
