### ISSUE TITLE
 is cluster supported?

### ISSUE THREAD

**Issue by erberry** [RedBeardLab/rediSQL#62]
is cluster supported?

**Comment by siscia** [comment]
Hi,

It should be!

Admittedly there is not too much testing on cluster because the inherent complexity and the fact that  this is the first time somebody ask. (Either it work flawless or nobody ever cared.)

In the first version I tested it, and it worked without hiccups, but there was some development, not substantial but some.

Also please be aware of what cluster means in the redis context. 

Cluster in redis is by key and in RediSQL a key is a database instance. You create a key with the command 

`REDISQL.CREATE_DB key_database_name`

So you are distributing databases in the cluster, not rows as in other "standard" databases.

This is suppose to works quite well if you partition your load in databases, as an example one db for each tenant of your application. Or one db for each high frequency data source, etc...

To wrap up.

Yes it is supported, not very well tested but nobody ever complained, if you find any bug we will fix them.

If you have any more questions please feel free to open another issue or follow up here if it is related to clustering.
Otherwise feel free to close the issue.

Cheers,
Simone

**Comment by siscia** [comment]
I believe I followed up via email.

Please feel free to close the issue.
