### ISSUE TITLE
issue of data sync in Slave using RediSQL

### ISSUE THREAD

**Issue by amitnakum** [RedBeardLab/rediSQL#91]
I setup Redis Replication Master-Slave by loading rediSQL_0.6.0.so module on both.I have configure redis Master for Write operation and Slave for only Read. 

whenever I write data on master, these changes are not reflecting on slave. But After restarting master those data are sync with slave.   

I Check Replication Write/Read operation using SET and GET command. When i set any key in master using set command, this key can read using get command immediately on slave without restart master service.

For more clear Understanding

Master output
-------------
[root@test1 ~]# redis-cli 
127.0.0.1:6379> REDISQL.QUERY xyz "select * FROM tbl_test"
 1)  1) (integer) 10
     2) "?????? 1"
     3) (integer) 44
     4) "172.16.16.84"
     5) (integer) 32
     6) (integer) 5060
     7) ""
     8) ""
     9) ""
    10) ""
    11) "UDP"
    12) (integer) 0
    13) ""
    14) "44:0"
    15) "IP"
    16) ""
    17) ""
    18) ""

Slave output
---------------

[root@test1 ~]# redis-cli -p 63790
127.0.0.1:63790> REDISQL.QUERY xyz "select * FROM tbl_test"
 1)  1) (integer) 10
     2) "?????? 1"
     3) (integer) 44
     4) "172.16.16.84"
     5) (integer) 32
     6) (integer) 5061
     7) ""
     8) ""
     9) ""
    10) ""
    11) "UDP"
    12) (integer) 0
    13) ""
    14) "44:0"
    15) "IP"
    16) ""
    17) ""
    18) ""

Here value 5060 and 5061 is different in master and slave.

Can you help to resolved this issue

**Comment by siscia** [comment]
Hi!

Can you try to monitor the two redis instances?

In order to monitor them open a new connection for the master and execute the `MONITOR` command and leave it there. Then open a new connection for the replica and execute against the replica, the `MONITOR` command, leave it there.

At this point try to modify the value in the master, both a standard value (eg `SET FOO 3`) and a RediSQL value (eg `REDISQL.EXEC ....whatever...`).

At this point can you paste the output of the two monitors?
